           <td>  <a href="http://hotels.mallorcaxlive.com/index.htm">HOME</a> |
                 <a href="http://hotels.mallorcaxlive.com/disclaimer/kontakt.htm">Kontakt</a> |
                 <a href="http://hotels.mallorcaxlive.com/disclaimer/faq.htm">FAQ</a> |
                 <a href="http://www.mallorcaxlive.com/disclaimer/werbung.htm">Werbung</a>

           </td>
         </tr>
</table>
</center>