  <table class="navi2">
    <tr>
      <td class="navi2_2">Hotelempfehlungen.
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/empfehlungen/5001.htm">Name Ort</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/empfehlungen/5002.htm">Name Ort</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/empfehlungen/5003.htm">Name Ort</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/empfehlungen/5004.htm">Name Ort</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/empfehlungen/5005.htm">Name Ort</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_2">Hotelkategorien
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kategorie/5_sterne.htm">5 Sterne *****</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kategorie/4_sterne.htm">4 Sterne ****</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kategorie/3_sterne.htm">3 Sterne ***</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kategorie/2_sterne.htm">2 Sterne **</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kategorie/1_sterne.htm">1 Stern *</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_2">Hoteltyp
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/typ/agrofinca.htm">Auf dem Land</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/typ/club.htm">In der Stadt</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/typ/fahrad.htm">Strandn&auml;he</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/typ/familien.htm">Luxus pur</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/typ/golf.htm">Wellnessoasen</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/typ/land.htm">Agrofinca</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/typ/luxus.htm">Clubanlagen</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/typ/stadt.htm">f&uuml;r Fahrardfahrer</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/typ/strand.htm">f&uuml;r Familien</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/typ/tagung.htm">f&uuml;r Golfer</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/typ/wander.htm">f&uuml;r Tagungen</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/typ/wellness.htm">f&uuml;r Wanderer</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_2">Hotellage
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/lage/palma.htm">Palma Stadt</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/lage/playa.htm">Playa de Palma</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/lage/tramutana.htm">Tramutana Gebirge</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/lage/mitte.htm">Inselmitte</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/lage/nord.htm">Norden & Nordosten</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/lage/ost.htm">Osten & S&uuml;dosten</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/lage/sued.htm">S&uuml;den</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/lage/suedwest.htm">S&uuml;dwesten & Westen</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/lage/nordwest.htm">Nordwesten</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/lage/ort/ortsliste.htm">Komplette Ortsliste</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_2">Hotelketten
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kette/acron.htm">Acorn</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kette/barcelo.htm">Barcel&oacute; Hotels & Resorts</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kette/best_western.htm">Best Western</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kette/dorint.htm">Dorint</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kette/garden_hotels.htm">Garden Hotels</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kette/grupotel.htm">Grupotel</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kette/hipotels.htm">Hipotels</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kette/hospes.htm">Hospes</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kette/hoteles_santos.htm">Hoteles Santos</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kette/iberostar.htm">Iberostar</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kette/mac.htm">Mac Hotels</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kette/mariott.htm">Marriott</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kette/melia.htm">Meli&aacute; Hotels & Resorts</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kette/oasis.htm">Oasis Hotels & Resorts</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kette/protour.htm">Protur</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kette/reis.htm">Reis de Mallorca</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kette/riu.htm">Riu Hotels</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kette/serrano.htm">Serrano Hotels</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kette/regis.htm">St. Regis</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kette/stein.htm"> Stein Hotels & Resorts</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kette/stil.htm">Stil Hotels & Resorts</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kette/starwood.htm">The Luxury Collection by Starwood</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/kette/tryp.htm">TRYP Hoteles</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_2">Alle Hotels Mallorca
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://hotels.mallorcaxlive.com/hotels/liste.htm">Komplette Hotelliste</a>
      </td>
    </tr>
  </table>