<center>
<table class="suche_navi1">
	<tr>
           <td class="suche_navi1_suche">Quickfinder <!--dropdown mit Orten fett darunter Namen mit Kategorie)-->
           </td>
           <td class="suche_navi1_navi1"> <a href="http://hotels.mallorcaxlive.com/typ/typ.htm">Hoteltyp</a> |
           				 <a href="http://hotels.mallorcaxlive.com/kategorie/kategorie.htm">Kategorie</a> |
                                          <a href="http://hotels.mallorcaxlive.com/lage/lage.htm">Hotellage</a> |
                                          <a href="http://hotels.mallorcaxlive.com/kette/kette.htm">Hotelkette</a> |
           				 <a href="http://www.mallorcaxlive.com/newsletter/newsletter.htm">Newsletter</a>
           </td>
         </tr>
</table>
</center>