<center>
<table class="footer">
	<tr>
           <td><hr noshade size="1" width="90%">
           </td>
         </tr>
	<tr>
           <td>
              <a href="http://mallorca.n-28.com/index.htm">HOME</a> |
              <a href="http://mallorca.n-28.com/disclaimer/kontakt.htm">Kontakt</a> |
              <a href="http://mallorca.n-28.com/disclaimer/faq.htm">FAQ</a> |
              <a href="http://mallorca.n-28.com/disclaimer/werbung.htm">Werbung</a> |
              <a href="http://mallorca.n-28.com/disclaimer/agb.htm">AGB</a> |
              <a href="http://mallorca.n-28.com/disclaimer/impressum.htm">Impressum</a> |
              <a href="http://mallorca.n-28.com/disclaimer/linkpartner.htm">Linkpartner</a>
           </td>
         </tr>
</table>
</center>