<center>
<table class="navi3top">
	<tr>
           <td>  <a href="http://mallorca.n-28.com/index.htm">HOME</a> |
                 <a href="http://mallorca.n-28.com/disclaimer/kontakt.htm">Kontakt</a> |
                 <a href="http://mallorca.n-28.com/disclaimer/faq.htm">FAQ</a> |
                 <a href="http://mallorca.n-28.com/disclaimer/werbung.htm">Werbung</a>

           </td>
         </tr>
</table>
</center>