  <table class="navi2">
    <tr>
      <td class="navi2_2">Mallorca Aktuell
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/aktuell/aktuelle_nachrichten/aktuelle_nachrichten.htm">Aktuelle Nachrichten</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/aktuell/promi_news/aktuelle_prominews.htm">Promi News</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/aktuell/newsletter/newsletter.htm">Newsletter</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/aktuell/mallorca_blog/blog.htm">Mallorca Blog</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/aktuell/veranstaltungskalender/veranstaltungskalender.htm">Veranstaltungskalender</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/aktuell/wetter/wetter.htm">Wetter</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/aktuell/webcam/webcam.htm">Webcam</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_2">Mallorca im &Uuml;berblick
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/ueberblick/allgemeine_infos/allgem_infos.htm">allgemeine Infos</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/ueberblick/geografie_geschichte/geografie_geschichte.htm">Geografie & Geschichte</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/ueberblick/menschen_mallorcas/menschen_mallorcas.htm">Menschen Mallorcas</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/ueberblick/gesundheitswesen/gesundheitswesen.htm">Gesundheitswesen</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/ueberblick/kultur_wirtschaft_bildung/kultur_wirtschaft_bildung.htm">Kultur, Wirtschaft & Bildung</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/ueberblick/verkehr_kommunikation/verkehr_kommunikation.htm">Verkehr & Kommunikation</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/ueberblick/recht_ordnung/recht_ordnung.htm">Recht & Ordnung</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/ueberblick/flora_fauna/flora_fauna.htm">Flora & Fauna</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/ueberblick/klima/klima.htm">Klima</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_2">Urlaub auf Mallorca
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/urlaub/allgemeine_infos/allgem_infos.htm">allgemeine Infos</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/urlaub/anreise/anreis.htm">Anreise</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/urlaub/unterkunft/unterkunft.htm">Unterk&uuml;nfte</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/urlaub/unternehmungen_reisetips/unternehmungen_reisetips.htm">Unternehmungen & Reisetips</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_2">Residenten auf Mallorca
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/residenten/allgemeine_infos/allgem_infos.htm">allgemeine Infos</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/residenten/arbeiten/arbeiten.htm">Arbeiten</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/residenten/wohnen/wohnen.htm">Wohnen</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/residenten/vereine_treffen/vereine_treffen.htm">Vereine & Treffen</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_2">Genie&szlig;en auf Mallorca
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/geniessen/allgemeine_infos/allgem_infos.htm">allgemeine Infos</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/geniessen/strand_hafen/strand_hafen.htm">Str&auml;nde & H&auml;fen</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/geniessen/kulinarisches/kulinarisches.htm">Kulinarisches</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/geniessen/wellness_sport/wellness_sport.htm">Wellness & Sport</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/geniessen/shopping/shopping.htm">Shopping</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/geniessen/nachtleben/nachtleben.htm">Nachtleben</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/geniessen/impressionen/impressionen.htm">Impressionen</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_2">Mallorca interaktiv
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/aktuell/mallorca_blog/blog.htm">Bloggers bienvenido</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/interaktiv/kleinanzeigen/kleinanzeigen.htm">Kleinanzeigen</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/interaktiv/gaestebuch/gaestebuch.htm">G&auml;stebuch</a>
      </td>
    </tr>
    <tr>
      <td class="navi2_3">&nbsp;&nbsp; <a href="http://mallorca.n-28.com/interaktiv/forum/forum.htm">Forum</a>
      </td>
    </tr>
  </table>