<center>
<table class="suche_navi1">
	<tr>
           <td class="suche_navi1_suche">Suchfeld
           </td>
           <td class="suche_navi1_navi1"> <a href="Navi 1">Hotel</a> |
           				 <a href="Navi 1">Finca</a> |
                                          <a href="Navi 1">Mietwagen</a> |
                                          <a href="Navi 1">Immobilien</a> |
           				 <a href="http://mallorca.n-28.com/aktuell/newsletter/newsletter.htm">Newsletter</a>
           </td>
         </tr>
</table>
</center>